const { getLocaleUrl } = require('../core/loadMetadata');

function section(title) {
  return `\n## ${title}\n\n`;
}

function generateMarkdown(metadata) {
  const { config, locales, screenshots, configuredLocales } = metadata;
  const lines = [];
  lines.push('# App Store Metadata Summary');
  lines.push('');
  lines.push('> Generated by YCAppStoreMetaKit. Edit source files under `AppStoreMetadata/`, not this file.');
  lines.push('');
  lines.push('## App Information');
  lines.push('');
  lines.push(`- Internal Name: ${config?.app?.internal_name || ''}`);
  lines.push(`- App Store Name: ${config?.app?.app_store_name || ''}`);
  lines.push(`- Bundle ID: ${config?.app?.bundle_id || ''}`);
  lines.push(`- SKU: ${config?.app?.sku || ''}`);
  lines.push(`- Apple ID: ${config?.app?.apple_id || ''}`);
  lines.push(`- Version: ${config?.app?.version || ''}`);
  lines.push(`- Platform: ${config?.app?.platform || ''}`);
  if (config?.app?.support_email) lines.push(`- Support Email: ${config.app.support_email}`);
  lines.push(`- Primary Category: ${config?.store?.primary_category || ''}`);
  lines.push(`- Secondary Category: ${config?.store?.secondary_category || ''}`);

  for (const locale of configuredLocales) {
    const data = locales[locale] || {};
    const m = data.metadata || {};
    lines.push(section(locale));
    lines.push('### Version Metadata');
    lines.push('');
    lines.push(`#### Name\n\n${m.name || ''}\n`);
    lines.push(`#### Subtitle\n\n${m.subtitle || ''}\n`);
    lines.push(`#### Promotional Text\n\n${m.promotional_text || ''}\n`);
    lines.push(`#### Description\n\n${m.description || ''}\n`);
    lines.push(`#### Keywords\n\n${m.keywords || ''}\n`);
    lines.push(`#### What\'s New\n\n${m.whats_new || ''}\n`);

    lines.push('### Legal URLs');
    lines.push('');
    lines.push(`- Privacy URL: ${getLocaleUrl(config, 'privacy', locale)}`);
    lines.push(`- Terms URL: ${getLocaleUrl(config, 'terms', locale)}`);
    lines.push(`- Support URL: ${getLocaleUrl(config, 'support', locale)}`);
    lines.push(`- Marketing URL: ${getLocaleUrl(config, 'marketing', locale)}`);

    lines.push('### Review Notes');
    lines.push('');
    lines.push(data?.review?.notes || '');

    lines.push('### Compliance Notes');
    lines.push('');
    lines.push(`#### Privacy Summary\n\n${data?.compliance?.privacy_summary || ''}\n`);
    lines.push(`#### Demo Content Notice\n\n${data?.compliance?.demo_content_notice || ''}\n`);

    lines.push('### Screenshot Copy');
    lines.push('');
    const sc = screenshots[locale]?.sets || {};
    for (const [setName, items] of Object.entries(sc)) {
      lines.push(`#### ${setName}`);
      lines.push('');
      (items || []).forEach((item, index) => {
        lines.push(`${index + 1}. **${item.title || ''}**`);
        lines.push(`   ${item.subtitle || ''}`);
      });
      lines.push('');
    }
  }

  return lines.join('\n').replace(/\n{4,}/g, '\n\n\n');
}

module.exports = {
  generateMarkdown
};
